/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jbnNbPq5xLDBHWcvGxJzGh
// Component: k94HjlCcI9KQ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/projectcss
import sty from "./PlasmicProcessCard.module.css"; // plasmic-import: k94HjlCcI9KQ/css

createPlasmicElementProxy;

export type PlasmicProcessCard__VariantMembers = {};
export type PlasmicProcessCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicProcessCard__VariantsArgs;
export const PlasmicProcessCard__VariantProps = new Array<VariantPropType>();

export type PlasmicProcessCard__ArgsType = {
  stepsNumber?: string;
  stepTitle?: string;
  stepDescription?: string;
};
type ArgPropType = keyof PlasmicProcessCard__ArgsType;
export const PlasmicProcessCard__ArgProps = new Array<ArgPropType>(
  "stepsNumber",
  "stepTitle",
  "stepDescription"
);

export type PlasmicProcessCard__OverridesType = {
  root?: Flex__<"div">;
  h4?: Flex__<"h4">;
};

export interface DefaultProcessCardProps {
  stepsNumber?: string;
  stepTitle?: string;
  stepDescription?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProcessCard__RenderFunc(props: {
  variants: PlasmicProcessCard__VariantsArgs;
  args: PlasmicProcessCard__ArgsType;
  overrides: PlasmicProcessCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          stepsNumber: "Step 1",
          stepTitle: "Step title",
          stepDescription: "Step Description"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__nJoNc
        )}
      >
        <React.Fragment>{$props.stepsNumber}</React.Fragment>
      </div>
      <h4
        data-plasmic-name={"h4"}
        data-plasmic-override={overrides.h4}
        className={classNames(
          projectcss.all,
          projectcss.h4,
          projectcss.__wab_text,
          sty.h4
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.stepTitle;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "Discovery & Strategy";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </h4>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__x44L3
        )}
      >
        <React.Fragment>{$props.stepDescription}</React.Fragment>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h4"],
  h4: ["h4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h4: "h4";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProcessCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProcessCard__VariantsArgs;
    args?: PlasmicProcessCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicProcessCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicProcessCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProcessCard__ArgProps,
          internalVariantPropNames: PlasmicProcessCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProcessCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProcessCard";
  } else {
    func.displayName = `PlasmicProcessCard.${nodeName}`;
  }
  return func;
}

export const PlasmicProcessCard = Object.assign(
  // Top-level PlasmicProcessCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h4: makeNodeComponent("h4"),

    // Metadata about props expected for PlasmicProcessCard
    internalVariantProps: PlasmicProcessCard__VariantProps,
    internalArgProps: PlasmicProcessCard__ArgProps
  }
);

export default PlasmicProcessCard;
/* prettier-ignore-end */
