/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jbnNbPq5xLDBHWcvGxJzGh
// Component: 7H0CNQCiTUwq

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/projectcss
import sty from "./PlasmicCardInfo.module.css"; // plasmic-import: 7H0CNQCiTUwq/css

import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: E1xFjJHiEMjj/icon

createPlasmicElementProxy;

export type PlasmicCardInfo__VariantMembers = {};
export type PlasmicCardInfo__VariantsArgs = {};
type VariantPropType = keyof PlasmicCardInfo__VariantsArgs;
export const PlasmicCardInfo__VariantProps = new Array<VariantPropType>();

export type PlasmicCardInfo__ArgsType = {
  nameOfCard?: string;
  shortDescription?: string;
  icons?: string;
};
type ArgPropType = keyof PlasmicCardInfo__ArgsType;
export const PlasmicCardInfo__ArgProps = new Array<ArgPropType>(
  "nameOfCard",
  "shortDescription",
  "icons"
);

export type PlasmicCardInfo__OverridesType = {
  root?: Flex__<"div">;
  svg?: Flex__<"svg">;
  h4?: Flex__<"h4">;
  text?: Flex__<"div">;
};

export interface DefaultCardInfoProps {
  nameOfCard?: string;
  shortDescription?: string;
  icons?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardInfo__RenderFunc(props: {
  variants: PlasmicCardInfo__VariantsArgs;
  args: PlasmicCardInfo__ArgsType;
  overrides: PlasmicCardInfo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          nameOfCard: "Title of the Card",
          shortDescription: "Your short description goes here"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <Icon4Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <h4
        data-plasmic-name={"h4"}
        data-plasmic-override={overrides.h4}
        className={classNames(
          projectcss.all,
          projectcss.h4,
          projectcss.__wab_text,
          sty.h4
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.nameOfCard;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "Custom Web Development";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </h4>
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.shortDescription;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "Bespoke websites built from scratch to meet your unique business needs. Fast, secure, and perfectly tailored to your brand.";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "h4", "text"],
  svg: ["svg"],
  h4: ["h4"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  h4: "h4";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCardInfo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCardInfo__VariantsArgs;
    args?: PlasmicCardInfo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCardInfo__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCardInfo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardInfo__ArgProps,
          internalVariantPropNames: PlasmicCardInfo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardInfo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardInfo";
  } else {
    func.displayName = `PlasmicCardInfo.${nodeName}`;
  }
  return func;
}

export const PlasmicCardInfo = Object.assign(
  // Top-level PlasmicCardInfo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    h4: makeNodeComponent("h4"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicCardInfo
    internalVariantProps: PlasmicCardInfo__VariantProps,
    internalArgProps: PlasmicCardInfo__ArgProps
  }
);

export default PlasmicCardInfo;
/* prettier-ignore-end */
