/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jbnNbPq5xLDBHWcvGxJzGh
// Component: 21IOWDabP3jT

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: BmEX1fFG6sB7/component
import CardInfo from "../../CardInfo"; // plasmic-import: 7H0CNQCiTUwq/component
import TemplateHolder from "../../TemplateHolder"; // plasmic-import: sd5mfsz4Jk5w/component
import ProcessCard from "../../ProcessCard"; // plasmic-import: k94HjlCcI9KQ/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jbnNbPq5xLDBHWcvGxJzGh/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 21IOWDabP3jT/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: OglyIqQmHBe4/icon
import ChevronDown2Icon from "./icons/PlasmicIcon__ChevronDown2"; // plasmic-import: KV6tc62Jiib0/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: E1xFjJHiEMjj/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navBar?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  hero?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  mainContainer?: Flex__<"div">;
  serviceIOffer?: Flex__<"section">;
  customWebDevelopment?: Flex__<typeof CardInfo>;
  customWebDevelopment2?: Flex__<typeof CardInfo>;
  customWebDevelopment3?: Flex__<typeof CardInfo>;
  whatYouCanDoThroughYourWebsite?: Flex__<"section">;
  processSteps?: Flex__<"section">;
  section?: Flex__<"section">;
  form?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
  input2?: Flex__<typeof AntdInput>;
  input3?: Flex__<typeof AntdInput>;
  textArea?: Flex__<typeof AntdTextArea>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,

        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "input3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "textArea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames(projectcss.all, sty.navBar)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__ghn70)}>
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"40px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"40px"}
                src={{
                  src: "/plasmic/freelance/images/image13.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <div className={classNames(projectcss.all, sty.freeBox__ySuOt)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__fzEsy
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Services"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__rIKd
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Templates"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__vAkVl
                  )}
                  component={Link}
                  href={"https://www.plasmic.app/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Process"}
                </PlasmicLink__>
                <Button
                  className={classNames("__wab_instance", sty.button__mNih0)}
                  color={"black"}
                  end={
                    <ChevronDown2Icon
                      className={classNames(projectcss.all, sty.svg__vPvdJ)}
                      role={"img"}
                    />
                  }
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d0B3Q
                      )}
                    >
                      {"Contact Us"}
                    </div>
                  }
                  start={
                    <CircleIcon
                      className={classNames(projectcss.all, sty.svg___2UFLb)}
                      role={"img"}
                    />
                  }
                />
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__dHzoK)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lvmI2
                  )}
                >
                  {"Stunning Websites for PNG SMEs"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yx469
                  )}
                >
                  {
                    "A website for your business to showcase your products, handle enquires and allow customers to book appointments."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__fiXat)}>
                <Button
                  className={classNames("__wab_instance", sty.button__olz2N)}
                  color={"white"}
                  end={
                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg__kiY5)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3A4Le
                      )}
                    >
                      {"Start now"}
                    </div>
                  }
                  size={"extraLarge"}
                  start={
                    <CircleIcon
                      className={classNames(projectcss.all, sty.svg__eFgCe)}
                      role={"img"}
                    />
                  }
                />
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"mainContainer"}
            data-plasmic-override={overrides.mainContainer}
            className={classNames(projectcss.all, sty.mainContainer)}
          >
            <section
              data-plasmic-name={"serviceIOffer"}
              data-plasmic-override={overrides.serviceIOffer}
              className={classNames(projectcss.all, sty.serviceIOffer)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__sDmk0)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__mr4Tt
                  )}
                >
                  {"Services I offer"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2Y0Ah
                  )}
                >
                  {
                    "From concept to launch, I provide everything you need for a successful online presence"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.columns__kTdeo)}>
                <div className={classNames(projectcss.all, sty.column___85PEq)}>
                  <CardInfo
                    data-plasmic-name={"customWebDevelopment"}
                    data-plasmic-override={overrides.customWebDevelopment}
                    className={classNames(
                      "__wab_instance",
                      sty.customWebDevelopment
                    )}
                    nameOfCard={"Custom Web Development"}
                    shortDescription={
                      "Bespoke websites built from scratch to meet your unique business needs. Fast, secure, and perfectly tailored to your brand."
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__tFQdt)}>
                  <CardInfo
                    data-plasmic-name={"customWebDevelopment2"}
                    data-plasmic-override={overrides.customWebDevelopment2}
                    className={classNames(
                      "__wab_instance",
                      sty.customWebDevelopment2
                    )}
                    nameOfCard={"E-commerce Solutions"}
                    shortDescription={
                      "Robust online stores that make selling products a breeze. I integrate secure payment gateways and intuitive inventory management."
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__o8Xr7)}>
                  <CardInfo
                    data-plasmic-name={"customWebDevelopment3"}
                    data-plasmic-override={overrides.customWebDevelopment3}
                    className={classNames(
                      "__wab_instance",
                      sty.customWebDevelopment3
                    )}
                    nameOfCard={"SEO & Performance"}
                    shortDescription={
                      "Get found on Google. I optimize every site for search engines and blazing-fast load times to improve user experience and rankings."
                    }
                  />
                </div>
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__xFq9V)}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__frKKt
                    )}
                  >
                    {"Learn More about my services"}
                  </div>
                }
              />
            </section>
            <section
              data-plasmic-name={"whatYouCanDoThroughYourWebsite"}
              data-plasmic-override={overrides.whatYouCanDoThroughYourWebsite}
              className={classNames(
                projectcss.all,
                sty.whatYouCanDoThroughYourWebsite
              )}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__dYxin
                )}
              >
                {"What you can accomplish on your website"}
              </h2>
              <div className={classNames(projectcss.all, sty.columns__yrCFa)}>
                <div className={classNames(projectcss.all, sty.column__rbYbj)}>
                  <TemplateHolder
                    className={classNames(
                      "__wab_instance",
                      sty.templateHolder__nkgLk
                    )}
                    templateDescription={
                      "You're Clients can book appointments through your website"
                    }
                    templateTittle={"Automate bookings"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___3IHhr)}>
                  <TemplateHolder
                    className={classNames(
                      "__wab_instance",
                      sty.templateHolder__hbDla
                    )}
                    templateDescription={
                      "A simple contact form is a powerful tool. Capture leads directly from your website and turn visitors into potential customers"
                    }
                    templateTittle={"Generate Online Enquiries"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__aYqZ)}>
                  <TemplateHolder
                    className={classNames(
                      "__wab_instance",
                      sty.templateHolder__e8EAw
                    )}
                    templateDescription={
                      "A mini store that displays your product and customer can place orders"
                    }
                    templateTittle={"Store layout"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___72OGw)}>
                  <TemplateHolder
                    className={classNames(
                      "__wab_instance",
                      sty.templateHolder__a65Ib
                    )}
                  />
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"processSteps"}
              data-plasmic-override={overrides.processSteps}
              className={classNames(projectcss.all, sty.processSteps)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__k8Tfr
                )}
              >
                {"4 steps  to get your Business Website"}
              </h2>
              <div className={classNames(projectcss.all, sty.columns__rKpud)}>
                <div className={classNames(projectcss.all, sty.column___7VQ7W)}>
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__fc826
                    )}
                    stepDescription={
                      "Step DescriptionWe start by discussing your business goals, target audience, and project requirements to create a solid plan for success."
                    }
                    stepTitle={"Discovery & Strategy"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__esb1H)}>
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__y04AX
                    )}
                    stepDescription={
                      "I'll create wireframes and mockups to visualize the website's structure and design, ensuring it aligns with your brand identity."
                    }
                    stepTitle={"Design & Prototyping"}
                    stepsNumber={"Step 2"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__iv51N)}>
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__gynw4
                    )}
                    stepDescription={
                      "Using modern technologies, I'll build a fast, responsive, and secure website from the approved designs."
                    }
                    stepTitle={"Development & Coding"}
                    stepsNumber={"Step 3"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__a2Da9)}>
                  <ProcessCard
                    className={classNames(
                      "__wab_instance",
                      sty.processCard__mVtLi
                    )}
                    stepDescription={
                      "After rigorous testing, we'll launch your website. I also offer ongoing support to ensure it runs smoothly."
                    }
                    stepTitle={"Launch & Support"}
                    stepsNumber={"Step 4"}
                  />
                </div>
              </div>
            </section>
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__z14PC)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__jw9Pi
                  )}
                >
                  {"Let's Build something Great"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Fv6Q
                  )}
                >
                  {
                    "Have a project in mind? Fill out the form below and I'll get back to you."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__k0Vi2)}>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.form),
                    extendedOnValuesChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["form", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],
                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onIsSubmittingChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["form", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["form"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "form.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "form.isSubmitting"
                      }
                    ],
                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <FormWrapper
                      data-plasmic-name={"form"}
                      data-plasmic-override={overrides.form}
                      {...child$Props}
                    >
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField__yrKby
                        )}
                        label={"Name"}
                        name={"name"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input),
                            onChange: async (...eventArgs: any) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            value: generateStateValueProp($state, [
                              "input",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input.value"
                              }
                            ],
                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdInput
                              data-plasmic-name={"input"}
                              data-plasmic-override={overrides.input}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField___4RSu1
                        )}
                        initialValue={"eg: Jonah's Photography"}
                        label={"Name of Business"}
                        name={"Name of Business"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input2),
                            onChange: async (...eventArgs: any) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input2", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            value: generateStateValueProp($state, [
                              "input2",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input2.value"
                              }
                            ],
                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdInput
                              data-plasmic-name={"input2"}
                              data-plasmic-override={overrides.input2}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField__vKDn
                        )}
                        initialValue={"eg: Jphotgraphy@gmail.com"}
                        label={"Email Address"}
                        name={"Email Address"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input3),
                            onChange: async (...eventArgs: any) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input3", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            value: generateStateValueProp($state, [
                              "input3",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input3.value"
                              }
                            ],
                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdInput
                              data-plasmic-name={"input3"}
                              data-plasmic-override={overrides.input3}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField__spaBm
                        )}
                        initialValue={
                          "Tell me what you want in your website, or ask me anything you wanna know"
                        }
                        label={"Message"}
                        name={"message"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames(
                              "__wab_instance",
                              sty.textArea
                            ),
                            onChange: async (...eventArgs: any) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["textArea", "value"],
                                AntdTextArea_Helpers
                              ).apply(null, eventArgs);
                            },
                            value: generateStateValueProp($state, [
                              "textArea",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "textArea.value"
                              }
                            ],
                            [],
                            AntdTextArea_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdTextArea
                              data-plasmic-name={"textArea"}
                              data-plasmic-override={overrides.textArea}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <AntdButton
                        className={classNames(
                          "__wab_instance",
                          sty.button__w1OnQ
                        )}
                        submitsForm={true}
                        type={"primary"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zaIxn
                          )}
                        >
                          {"Submit"}
                        </div>
                      </AntdButton>
                    </FormWrapper>
                  );
                })()}
              </div>
            </section>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "img",
    "hero",
    "foreground2",
    "mainContainer",
    "serviceIOffer",
    "customWebDevelopment",
    "customWebDevelopment2",
    "customWebDevelopment3",
    "whatYouCanDoThroughYourWebsite",
    "processSteps",
    "section",
    "form",
    "input",
    "input2",
    "input3",
    "textArea"
  ],
  navBar: ["navBar", "img"],
  img: ["img"],
  hero: ["hero", "foreground2"],
  foreground2: ["foreground2"],
  mainContainer: [
    "mainContainer",
    "serviceIOffer",
    "customWebDevelopment",
    "customWebDevelopment2",
    "customWebDevelopment3",
    "whatYouCanDoThroughYourWebsite",
    "processSteps",
    "section",
    "form",
    "input",
    "input2",
    "input3",
    "textArea"
  ],
  serviceIOffer: [
    "serviceIOffer",
    "customWebDevelopment",
    "customWebDevelopment2",
    "customWebDevelopment3"
  ],
  customWebDevelopment: ["customWebDevelopment"],
  customWebDevelopment2: ["customWebDevelopment2"],
  customWebDevelopment3: ["customWebDevelopment3"],
  whatYouCanDoThroughYourWebsite: ["whatYouCanDoThroughYourWebsite"],
  processSteps: ["processSteps"],
  section: ["section", "form", "input", "input2", "input3", "textArea"],
  form: ["form", "input", "input2", "input3", "textArea"],
  input: ["input"],
  input2: ["input2"],
  input3: ["input3"],
  textArea: ["textArea"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: "div";
  img: typeof PlasmicImg__;
  hero: "div";
  foreground2: "div";
  mainContainer: "div";
  serviceIOffer: "section";
  customWebDevelopment: typeof CardInfo;
  customWebDevelopment2: typeof CardInfo;
  customWebDevelopment3: typeof CardInfo;
  whatYouCanDoThroughYourWebsite: "section";
  processSteps: "section";
  section: "section";
  form: typeof FormWrapper;
  input: typeof AntdInput;
  input2: typeof AntdInput;
  input3: typeof AntdInput;
  textArea: typeof AntdTextArea;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    img: makeNodeComponent("img"),
    hero: makeNodeComponent("hero"),
    foreground2: makeNodeComponent("foreground2"),
    mainContainer: makeNodeComponent("mainContainer"),
    serviceIOffer: makeNodeComponent("serviceIOffer"),
    customWebDevelopment: makeNodeComponent("customWebDevelopment"),
    customWebDevelopment2: makeNodeComponent("customWebDevelopment2"),
    customWebDevelopment3: makeNodeComponent("customWebDevelopment3"),
    whatYouCanDoThroughYourWebsite: makeNodeComponent(
      "whatYouCanDoThroughYourWebsite"
    ),
    processSteps: makeNodeComponent("processSteps"),
    section: makeNodeComponent("section"),
    form: makeNodeComponent("form"),
    input: makeNodeComponent("input"),
    input2: makeNodeComponent("input2"),
    input3: makeNodeComponent("input3"),
    textArea: makeNodeComponent("textArea"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
